apiVersion: v1
kind: Service
metadata:
  name: srv1
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80  # The port on the service
      targetPort: 8080  # The port on your pods
  type: ClusterIP
